[tool.black]
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
skip_gitignore=true

[tool.ruff]
select = ["ALL"]
ignore = [
    "ANN101", "ANN204", "ANN401",
    "D104", # no docstring in public package
    "D",
    "D1",
    "RSE102",
    "FLY002", # fix produces invalid code https://github.com/astral-sh/ruff/issues/5150
    "E501", # black will take care about it
    "INP001",
]
target-version = "py311"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
