[tool.black]
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
skip_gitignore=true

[tool.ruff]
select = ["ALL"]
ignore = [
    "ANN101", "ANN204", "ANN401",
    "D104", # no docstring in public package
    "D200", # One-line docstring should fit on one line with quotes
    "D212",
    "RSE102",
    "D203",
    "FLY002", # fix produces invalid code https://github.com/astral-sh/ruff/issues/5150
    "E501", # black will take care about it
]

target-version = "py311"
